### ISSUE TITLE
Create first draft of general diagram of components

### ISSUE THREAD

**Issue by jackiekazil** [18F/2015-foia#10]
Create general diagram of components as they relate to each other.

**Comment by jackiekazil** [comment]
This is super ugly and drafty... but it might be helpful. This is a first draft & as such is already out of date. 
![foia-app-diagram-20140714-v2](https://cloud.githubusercontent.com/assets/166734/3629582/31634bb6-0ea2-11e4-9ac2-cf75969e4123.png)

**Comment by jackiekazil** [comment]
p.s. ... I am not a designer.

**Comment by corizarek** [comment]
This is awesome! So glad you shared -- great to get a sense of what the team is noodling over. (And it looks waaaayy nicer than I could have done!) Keep 'em coming!

**Comment by nsinai** [comment]
:+1:
