### ISSUE TITLE
FOIA Url not working

### ISSUE THREAD

**Issue by ghost** [18F/2015-foia#118]
The following url https://18f.gsa.gov/site/18F/18f.gsa.gov/tags/foia/
gives a 404 error

**Comment by vz3** [comment]
That URL appears to be malformed. Where did you see this linked from?

It should likely point to: https://18f.gsa.gov/tags/foia/

**Comment by ghost** [comment]
@vz3 Thanks Victor

**Comment by webmaven** [comment]
I think this issue can be closed.
