### ISSUE TITLE
Discuss FOIA project deployment & create tickets to make it happen

### ISSUE THREAD

**Issue by jackiekazil** [18F/2015-foia#15]
We should talk about how we want to handle deployment for this project. 
Ideas very very briefly discussed:
- Separate repo to deploy components to deploy all?
- Ansible? Salt?

/cc @konklone 
b/c @NoahKunin might also be interested.

**Comment by konklone** [comment]
Let's talk this out in Slack and see what others are doing with multi-component deployments.
