### ISSUE TITLE
Common data model for FOIA requests?

### ISSUE THREAD

**Issue by vdavez** [18F/2015-foia#2]
I don't know if this is the venue or wildly out of scope, but I would love to see mature data modeling/standardization around FOIA data.

This would include public-facing data (requester, date of request, nature of request, etc.), process data (response time, exemptions invoked, etc.), and agency-facing data (user, search terms used, etc.).

Even having a public conversation about what types of FOIA data should be collected, maintained, would be a helpful start.

**Comment by waltz** [comment]
I think this is a great idea. I'm a little worried that different stakeholders would have wildly different requirements, though I think we should definitely try to hash something out.

**Comment by konklone** [comment]
I don't think it's out of scope at all. Hashing out a schema is probably the most important first step to interoperability, in any context. 

I'm sure requirements would differ a lot, though at the US federal level, even standardizing across agencies would be a huge win. @waltz, how do you make RecordTrac work across different clients? 

I need to Take To The Wiki soon to flesh out my ideal federated architecture of FOIA, but in my head the main points of interoperability where a schema would be helpful are something like:
- A request is opened. Get it to an agency!
- An open request exists. The agency and requestor are interacting! (Request state is changing!)
- A request has been closed. Here are the documents!

I also think something for the records themselves, that can stand on its own, is helpful in creating a pipeline of public records that's at least conceptually separate from the actual process by which they were created. (You can imagine having FOIA-released documents surfacing in other search engines that have nothing to do with FOIA.) That seems like the lightest-weight schema, to the point of being dangerously close to RSS.

**Comment by DanielSchuman** [comment]
Eric,

There may be bullet points between 2 and 3.

Such as:
- the request came to the wrong component within an agency. Bounce it.
- more than one agency has equities in the records. For example, it's held
  by agency a, but came from classified material from agency b.  Process as
  agency a; then send to agency b for them to process, then return.

Etc.

Daniel

**Comment by vdavez** [comment]
To pick up on @waltz's comment.My sense is that we should start small: identify obvious data points, and then build up. Add complexity as needed, but agree on minimums first.

**Comment by konklone** [comment]
I'd love to pick this back up. @waltz, is there anything you like from RecordTrac's request or response schema?

**Comment by vdavez** [comment]
Picking back up on this. @waltz @konklone. So, let's start with the basics and actually mock something up? I've started a wiki https://github.com/18F/foia/wiki/Common-data-model-for-FOIA-requests to try and spur conversation?

**Comment by konklone** [comment]
Awesome, @vzvenyach -- I just went and did another pass over it, adding and updating a bunch of stuff:

https://github.com/18F/foia/wiki/Common-data-model-for-FOIA-requests

I'm sure it's missing a lot of things. @waltz, maybe you have some ideas for it?

**Comment by jeremiak** [comment]
How might this work if a back and forth is required between the requestor and the FOI liaison at the agency? I understand that there would be an initial request, and then a response (multiple responses can be linked to a request), but in my experience of making open records requests I have to go back and forth with the agency in order to get the documents I want. How can I model a single threaded conversation with this data model? Is that even important?

**Comment by vdavez** [comment]
I suppose there are a few ways we could do it. We could (1) just update the request, (2) store the previous request information as a part of the request object, or (3) use `dat` or something similar to maintain the earlier versions?

**Comment by konklone** [comment]
This conversation seems to have stalled. I'm going to close, but I think it we'll reboot it in the near future (and anyone who wants to keep talking about this can re-open).
