### ISSUE TITLE
Common FOIA Regulations

### ISSUE THREAD

**Issue by DanielSchuman** [18F/2015-foia#20]
As part of 18F's work on FOIA, I thought it would be helpful to flag efforts to create common FOIA regulations. In other words, a single set of regulations that would govern how all agencies implement many aspects of FOIA. 

The effort to develop model FOIA regulations was outlined in the administration's second national action plan ([See item #3, bullet point #2](http://www.whitehouse.gov/sites/default/files/docs/us_national_action_plan_6p.pdf)). The Department of Justice's Office of Information policy is coordinating the multi-agency multi-stakeholder process.

A group of non-profit organizations that regularly litigate on FOIA have put together [model common FOIA regulations](http://www.modelfoiaregs.org/), which hopefully will serve as a starting point for agency/stakeholder deliberations.

**Comment by nsinai** [comment]
This is great, thanks for the contribution!

**Comment by rjmajma** [comment]
Hey Daniel, thanks for the comment. Working on model common FOIA regs is actually outside of our scope, but I've made sure to share this comment and the site you linked to with some of our colleagues at DOJ. Thanks for help!
