### ISSUE TITLE
List of all agencies' FOIA libraries and materials

### ISSUE THREAD

**Issue by konklone** [18F/2015-foia#21]
One doesn't exist right now, for US federal agencies. This is a pretty good discrete task that just about anyone could do: find them and put them in a spreadsheet.

Fields worth collecting for each agency (or other discrete FOIA publishing unit):
- URL of the library or libraries
- Whether an API or bulk data is officially provided (probably doesn't exist anywhere)
- Difficulty of scraping it (e.g. unofficial API <--> paginated URLs with permalinks <--> non-permalinked form navigation)
- How complete is the library?
- Updated automatically, or with careful discretion?
- Is metadata about the original request/response included alongside the document (and document-level metadata)?

**Comment by konklone** [comment]
Just found this: http://www.ifoia.com/index.php/electronic-reading-rooms

**Comment by ErieMeyer** [comment]
Might be an interesting NAP item to get these posted in /digitalstrategy.json, and create an API of these @corizarek=

**Comment by corizarek** [comment]
Nice find @konklone and very interesting thought, @ErieMeyer -- let's discuss!

**Comment by konklone** [comment]
@khandelwal heroically took this one and added this data to our work in #62.

**Comment by BigSecz** [comment]
I am the creator of iFOIA.com.  Let me know if you have any questions.
