### ISSUE TITLE
FOIA request intake API

### ISSUE THREAD

**Issue by konklone** [18F/2015-foia#25]
I'd love community input, now and ongoing, on where we should take our FOIA request intake API should look.

Our current FOIA request intake API, [as deployed](http://foia.18f.us/request/general-services-administration/), looks like this:
### `/api/request/`

Accepts POSTs with POST bodies containing JSON like this:

``` json
{
  "first_name": "Eric",
  "last_name": "Mill",
  "email": "eric.mill@gsa.gov",
  "body": "Body of the request",
  "documents_start": "September 9, 2014",
  "documents_end": "September 11, 2014",
  "fee_limit": 20,
  "agency_fields": {
    "region": "3A",
    "contract": "GS-12345"
  },
  "agency": "general-services-administration",
  "office": "headquarters"
}
```

Thoughts on the request:
- The schema is obviously going to be expanding as we add fields, and agency-specific fields. The schema will be more loosely defined for agency-specific fields.
- We need to get documentation up: what fields are required and optional, what type a field needs to be, and any constraints and enumerations on field values.
- `agency_fields` rubs me the wrong way aesthetically for an API - `agency_specific` or even just `agency` (where the current `agency` and `office` fields get moved into this object) would be better for API clients, I think.

For successful requests, it returns a response with a `201 Created` status code, and a JSON body like this:

``` json
{
  "fee_limit": 0,
  "custom_fields": {
    "region": "3A",
    "contract": "GS-12345"
  },
  "date_end": "2014-09-11T00:00:00",
  "status": "O",
  "requester": 4,
  "tracking_id": 2,
  "date_start": "2014-09-09T00:00:00",
  "request_body": "Testing"
}
```

Thoughts on the success response:
- The response uses inconsistent field names from the request, which should be changed. 
- Some of them: `date_start`, `date_end`, `request_body`, `custom_fields`, `fee_limit`, and even `status` (assuming it's always `O` for new requests) are not needed here. 
- It's not obvious what the `requester` field is.
- Our `tracking_id` should be something besides a database autoincrement (and be a string instead of a number).

For an unsuccessful response, we return a `500` status code and a JSON body including a Django stack trace. We should update that to handle errors in a graceful, predictable way.

**Comment by aarongraves** [comment]
There should be address fields included. 

If you are going to include a Fee Waiver box, then you should also include an Expedite Request box. HOWEVER, there should be some additional information included under each section. Sure, anyone can ask for it, but there are only certain/specific instances when it is granted. Including that language WILL cut down in the number of those seeking relief in either category.

**Comment by konklone** [comment]
@aarongraves Yep, we'll be adding address fields to our form, so they should get in the API, thanks for mentioning that here. Same for Expedition, which will come with a UX challenge to make it easy, but clear that it's not for every request. You can discuss and track our implementation of new form fields over at https://github.com/18F/foia-hub/issues/34.

**Comment by konklone** [comment]
Much work has been done on this by @jackiekazil and @khandelwal in the [foia-hub repo](https://github.com/18F/foia-hub), including technical documentation. It's not publicly documented, and not receiving requests actively yet, but discussion should move over to that repo and be focused on more specific elements.
