### ISSUE TITLE
'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by geramirez** [18F/2015-foia#55]
I was trying to update the manual data when I got this error message. I reset from master, but the error persisted.

```
INFO:root:[Treasury] Already downloaded.
Traceback (most recent call last):
  File "scraper.py", line 391, in <module>
    save_agencies()
  File "scraper.py", line 360, in save_agencies
    save_agency(agency)
  File "scraper.py", line 338, in save_agency
    data = parse_agency(abb, BeautifulSoup(text))
  File "scraper.py", line 210, in parse_agency
    departments.append(parse_department(elem, dept_name))
  File "scraper.py", line 187, in parse_department
    for key, value in find_bold_fields(ps):
  File "scraper.py", line 144, in find_bold_fields
    value = strong.next_sibling.string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by konklone** [comment]
This is from the scraper, not the manual data. This looks like the scraper's `strong` element was expected to have a `next_sibling` but doesn't, meaning maybe the FOIA.gov HTML changed. Care to dig in?

**Comment by cmc333333** [comment]
If it's any help, I still have some of the previously scaped files for comparison.

**Comment by jackiekazil** [comment]
This ticket should be in foia-hub no?

**Comment by geramirez** [comment]
@konklone, I'll start taking a look

**Comment by geramirez** [comment]
I think this should fix the issue [PR 57](https://github.com/18F/foia/pull/57)

**Comment by geramirez** [comment]
Closed with PR 57(https://github.com/18F/foia/pull/57)
