### ISSUE TITLE
Make design previews and mockups easy to find

### ISSUE THREAD

**Issue by nsinai** [18F/2015-foia#66]
Right now the ReadMe points to a different "design" repo -- which is "retired" and points back to this repo!

It should be easy for any new user -- technical or non-technical -- to check out what the product/website looks like (or what the most recent alpha/beta looked like).

**Comment by konklone** [comment]
:+1: Probably more of a @vz3 or @jtag question, but yes.

**Comment by rjmajma** [comment]
Thanks, as always, for the suggestion Nick. We're working on better ways to sync up how we display our design work in anticipation of our initial public release. We'll make sure to tag it here once it's up.

And thanks for catching the readme mistake.

**Comment by khandelwal** [comment]
I also created this yesterday in a parallel universe to @nsinai https://github.com/18F/foia-hub/issues/310

**Comment by konklone** [comment]
Closing in favor of focusing on https://github.com/18F/foia-hub/issues/310

**Comment by nsinai** [comment]
Thanks!
